typography_spectrum: 0.1391721076797694
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9665624212939292
analytics:
  google: null
  facebook: null
  twitter: null
name: Vehicle Wraps in Kansas City
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Vehicle Wraps by REV2
purpose: []
