typography_spectrum: 0.1391721076797694
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9665624212939292
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/48ee4038-6b9a-4778-bbd1-169e57916ff1.png
name: Vehicle Wraps in Kansas City
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2c4fef3d-80a4-4c7b-888f-a734641fdcc2.png
title: Vehicle Wraps by REV2
purpose: []
